<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'AcMailer\Service\Factory\MailServiceFactory' => __DIR__ . '/src/AcMailer/Service/Factory/MailServiceFactory.php',
  'AcMailer\Service\MailService'                => __DIR__ . '/src/AcMailer/Service/MailService.php',
  'AcMailer\Service\MailServiceAwareInterface'  => __DIR__ . '/src/AcMailer/Service/MailServiceAwareInterface.php',
  'AcMailer\Service\MailServiceMock'            => __DIR__ . '/src/AcMailer/Service/MailServiceMock.php',
  'AcMailer\Service\MailServiceInterface'       => __DIR__ . '/src/AcMailer/Service/MailServiceInterface.php',
  'AcMailer\Event\MailListener'                 => __DIR__ . '/src/AcMailer/Event/MailListener.php',
  'AcMailer\Event\MailListenerAwareInterface'   => __DIR__ . '/src/AcMailer/Event/MailListenerAwareInterface.php',
  'AcMailer\Event\MailEvent'                    => __DIR__ . '/src/AcMailer/Event/MailEvent.php',
  'AcMailer\Options\Factory\MailOptionsFactory' => __DIR__ . '/src/AcMailer/Options/Factory/MailOptionsFactory.php',
  'AcMailer\Options\MailOptionsAwareInterface'  => __DIR__ . '/src/AcMailer/Options/MailOptionsAwareInterface.php',
  'AcMailer\Options\TemplateOptions'            => __DIR__ . '/src/AcMailer/Options/TemplateOptions.php',
  'AcMailer\Options\MailOptions'                => __DIR__ . '/src/AcMailer/Options/MailOptions.php',
  'AcMailer\Exception\InvalidArgumentException' => __DIR__ . '/src/AcMailer/Exception/InvalidArgumentException.php',
  'AcMailer\Result\MailResult'                  => __DIR__ . '/src/AcMailer/Result/MailResult.php',
  'AcMailer\Result\ResultInterface'             => __DIR__ . '/src/AcMailer/Result/ResultInterface.php',
  'AcMailer\Module'                             => __DIR__ . '/Module.php',
);
