<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'AcMailer\Module'                             => __DIR__ . '/Module.php',
  'AcMailer\Exception\InvalidArgumentException' => __DIR__ . '/src/AcMailer/Exception/InvalidArgumentException.php',
  'AcMailer\Options\MailOptions'                => __DIR__ . '/src/AcMailer/Options/MailOptions.php',
  'AcMailer\Options\MailOptionsAwareInterface'  => __DIR__ . '/src/AcMailer/Options/MailOptionsAwareInterface.php',
  'AcMailer\Result\MailResult'                  => __DIR__ . '/src/AcMailer/Result/MailResult.php',
  'AcMailer\Result\ResultInterface'             => __DIR__ . '/src/AcMailer/Result/ResultInterface.php',
  'AcMailer\Service\Factory\MailServiceFactory' => __DIR__ . '/src/AcMailer/Service/Factory/MailServiceFactory.php',
  'AcMailer\Service\MailService'                => __DIR__ . '/src/AcMailer/Service/MailService.php',
  'AcMailer\Service\MailServiceInterface'       => __DIR__ . '/src/AcMailer/Service/MailServiceInterface.php',
  'AcMailer\Service\MailServiceMock'            => __DIR__ . '/src/AcMailer/Service/MailServiceMock.php',
);
